name: Publish NPM Package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Clean up dist directory
        run: rm -rf dist

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public --loglevel verbose
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
